version: 0.2

env:
  parameter-store:
    #     BUCKET_NAME: "BUCKET_NAME"
    DIST_ID: "DIST_ID"
    SERVER_URL: "SERVER_URL"

phases:
  pre_build:
    commands:
      - cd client
      - npm install
      - echo npm install succeeded
    finally:
      - echo prebuild completed
  build:
    commands:
      - npm run build
      - echo build succeeded
      # - aws s3 rm s3://${BUCKET_NAME} --recursive
      # - echo s3 bucket objects removed
    finally:
      - echo build completed
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id ${DIST_ID} --paths '/*'
      - echo cloudfront invalidation completed
      - echo Build Completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: client/dist
