version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - rm -rf node_modules
      - rm package-lock.json
      - npm install
      - echo npm install succeeded
    finally:
      - echo prebuild completed
  build:
    commands:
      - npm run build
      - echo build succeeded
    finally:
      - echo build completed
  post_build:
    commands:
      - echo Build Completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: client/dist
