version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install
      - echo npm install succeeded
    finally:
      - echo prebuild completed
  build:
    commands:
      - npm run build
      - echo build succeeded
      - aws s3 sync --delete . "s3://myjourney-client"
    finally:
      - echo build completed
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E2RE6ZCH0T35FW --paths '/*'
      - echo Build Completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: client/dist
